title: Scott Krulcik
email: scott@scottkrulcik.com
description: >
    Scott Krulcik's personal website.
baseurl: ""
url: "https://scottkrulcik.com" # the base hostname & protocol for your site
github_username: skrulcik

markdown: kramdown
